version: "3"

services:
  db:
    image: mariadb:10.2 # Compatible with MySQL 5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db:/var/lib/mysql

  wp:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${WP_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html
      - ./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
